baseurl      = "https://nathancatania.com"
title        = "Nathan Catania"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 15

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 +1000"

  # Subtitle for home
  homeSubtitle = "Engineer // Melbourne // Australia"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "The official website of Nathan Catania &#10003;"
  keywords = "homepage, blog, website, official, engineer, saas, zscaler, security, juniper, telstra, sales, se"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/nathancatania/website/commit/"

  # Social icons
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nathancatania"

  [[params.social]]
    name = "email"
    url  = "mailto:hello@nathancatania.com"

  

[Author]  
  name = "Nathan Catania" 
  email = "hello@nathancatania.com"   
  bio = "Engineer // Melbourne // Australia"  
  [Author.photo]    
    url = "avatar.png" 



[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[languages]
  [languages.en]
    title = "Nathan Catania"
    subtitle = "Engineer // Melbourne // Australia"
    keywords = "blog, website, official"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/nathan"
      logoHomeLink = "/"
    # or
    #
    # path = "https://www.svgrepo.com/show/50992/xing-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"